image: "gcc"
before_script:
  - apt update && apt -y install cmake

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j2
  artifacts:
    paths:
      - build

test:
  stage: test
  script:
    - cd build
    - make test

